server:
  servlet:
    context-path: /api

spring:
  datasource:
      url: jdbc:sqlserver://localhost:1433;databaseName=sh;encrypt=true;trustServerCertificate=true
      username: root
      password: root
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      hikari:
        minimum-idle: 5           #Connection Pool에 유지 가능한 최소 커넥션 개수
        maximum-pool-size: 10     #Connection Pool에 유지 가능한 최대 커넥션 개수
        idle-timeout: 30000       #Connection이 Poll에서 유휴상태(사용하지 않는 상태)로 남을 수 있는 최대 시간
        pool-name: HyoHikariCP    #Connction Pool 이름
        max-lifetime: 200000      #Connection의 최대 유지 가능 시간
        connection-timeout: 30000 #Pool에서 Connection을 구할 때 대기시간, 대기시간안에 구하지 못하면 Exception

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate.format_sql: true

  profiles:
    default: local
